### ISSUE TITLE
Bug - Missing evaluation files

### ISSUE THREAD

**Issue by MatanArgaman** [Dinstein-Lab/ASDSpeech#1]
Hi,
The repository data files are missing the data_T{i+1}**_info**.xlsx files which are read at 
python code/estimate_recs_trained_mdl.py line 85.

**Comment by marinaEni** [comment]
Thank you for your comment. The bug is fixed, it was supposed to be written data_T{i+1}.xlsx (without _info).

**Comment by MatanArgaman** [comment]
Hi Ilan and Marina,
I ran the same code again and it still errors, I opened a new issue
<https://github.com/Dinstein-Lab/ASDSpeech/issues/2>.
It seems that you're merging two tables (line 140) which don't have all
matching indices, resulting in NaNs.
Thanks,
Matan

**Comment by MatanArgaman** [comment]
+ Marina

Hi Ilan and Marina,
I ran the same code again and it still errors, I opened a new issue
<https://github.com/Dinstein-Lab/ASDSpeech/issues/2>.
It seems that you're merging two tables (line 140) which don't have all
matching indices, resulting in NaNs.
Thanks,
Matan

**Comment by MatanArgaman** [comment]
Hello Matan,
I fixed the bug.

I added a row:
test_df['rec_id'] = test_df['rec_id'].astype(str)
after:
test_df = test_sets_df[test_set]

Good luck,
Marina
